### ISSUE TITLE
本リポジトリの保護について

### ISSUE THREAD

**Issue by zinntikumugai** [BitzenyCoreDevelopers/BitzenycoreDevelopers.github.io#31]
このリポジトリはbranchに対して保護設定を行っていないため、masterへのmergeの規定が無く権限さえあればチェックなしでmerge出来ます(自己PR承認)

しかし、公式ページとなるリポジトリですのでmaster保護並びPR mergeの規定(どちらかと言えばコードのチェック)を設けたいと思いたいですがいかがでしょうか

具体的には
- Require pull request reviews before merging
  - PRには承認が必須
- Include administrators
  - 管理者であっても承認なしのmerge無効

参考
 - [[GitHub] ブランチの保護設定を活用しよう 【レビューが通るまでマージさせんぞ】
](https://dev.classmethod.jp/tool/github/protect-branch/)

**Comment by zinntikumugai** [comment]
あと、このリポジトリ上ですべて終わらせるのもなんとも言えない
各自のリポでフォークして修正、PR、承認がいいのでは?

**Comment by BitzenyDevTeam** [comment]
良いですね！
賛成です。

**Comment by cryptomamiya** [comment]
Master branch にprotected branchのルール適用ってことだよね。
是非ともやりましょう。
適用ルールも上記2つでOKだと思います。
Reviewer必要数はとりあえず1がいいかな…

**Comment by kazu0617** [comment]
自分も賛成です。
Reviewer数はマージリクエスト本人を除く1名を自分も希望します

**Comment by zinntikumugai** [comment]
だいぶ経ってしまいましたが、賛成が多数なので設定したいと思います
Reviewer数は1で様子見たいと思います
